name: CI for Go

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

    #   - name: Run tests
    #     run: go test -v ./...

      - name: Run go vet
        run: go vet ./...

      # - name: Run golint
      #   uses: golangci/golangci-lint-action@v6
      #   with:
      #     version: v1.55.2  # Use latest from https://github.com/golangci/golangci-lint/releases
      #     args: run ./...

      - name: Run staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
