name: Lint with reviewdog

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run linters with reviewdog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      ############################################
      # 1. golangci-lint + reviewdog
      ############################################
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin v1.55.2
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Run golangci-lint with reviewdog
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--timeout=2m"
          level: warning
          reporter: github-pr-review
          fail_on_error: false

      ############################################
      # 2. staticcheck + reviewdog
      ############################################
      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run staticcheck with reviewdog
        uses: reviewdog/action-staticcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          fail_on_error: false

      ############################################
      # 3. go fmt + reviewdog
      ############################################
      - name: Run gofmt with reviewdog
        uses: reviewdog/action-gofmt@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          fail_on_error: false
